FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json postcss.config.mjs globals.css ./


COPY apps ./apps
COPY packages ./packages


# Can you add a script to the global package.json that does this?
RUN cd packages/db && npx prisma generate && cd ../..
RUN npm install

# Can you filter the build down to just one app?
RUN npm run build 

CMD ["npm", "run", "start-user-app"]

